config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, sign_out_via: [ :get, :delete ]

  # devise_for :users
  devise_for :users, sign_out_via: [ :get, :delete ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
  get "/about", to: "pages#about"
  get "/news", to: "pages#news"
  get "/single_news", to: "pages#single_news"
  get "/contact", to: "pages#contact"
  get "/single_product", to: "pages#single_product"
  # get "/cart", to: "pages#cart"
  get "/checkout", to: "pages#checkout"
  get "/404", to: "pages#error_404"
  resources :products, except: [ :index ]
  # go to the products in a certain category
  get "/products/category/:category", to: "products#cat_products", as: :products_by_category
  get "/shop", to: "products#shop"


  post "/cart/add/:product_id", to: "carts#add_item", as: :add_to_cart
  get "/cart", to: "carts#show", as: :cart

  resources :cart_items, only: [ :destroy ]




  draw :admin
end

def draw(routes_name)
  instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  validates :status, inclusion: { in: %w[active ordered] }
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :cart_items

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :stock_quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # optional helper to get image URL
  def image_url
    image_path.presence || "default-product.jpg"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
end

app/controllers/CartItemsController.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_path, notice: "Item removed"
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  # stale_when_importmap_changes

  # Tell Devise to use the main layout
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "application"  # <- uses your normal layout
    else
      "application"
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

def add_item
  product = Product.find(params[:product_id])

  quantity = params[:quantity].to_i
  quantity = 1 if quantity <= 0

  cart = current_user.cart || current_user.create_cart(status: "active")

  cart_item = cart.cart_items.find_by(product_id: product.id)

  if cart_item
    cart_item.quantity += quantity
    cart_item.save
  else
    cart.cart_items.create!(
      product: product,
      quantity: quantity,
      price_at_time: product.price
    )
  end

  redirect_back fallback_location: root_path, notice: "Product added to cart"
end

  def show
    @cart = current_user.cart
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [ :cart, :checkout ]
  layout false, only: [ :home ]
  def home
    @categories = Category.all
  end

  def about
  end

  def news
  end

  def contact
  end

  def single_news
  end

  def single_product
  end

  def cart
  end

  def checkout
  end

  def error_404
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]

  # GET /products
  def cat_products
    if params[:category]
      @category = Category.find_by(name: params[:category])

      if @category
        @products = @category.products
      else
        @products = Product.none
      end
    else
      @products = Product.none
    end
  end

  # GET /products/:id
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /products/:id/edit
  def edit
  end

  # PATCH/PUT /products/:id
  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/:id
  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end


 def shop
    @categories = Category.all

    if params[:category].present?
      @selected_category = Category.find_by(name: params[:category])
      @products = @selected_category&.products&.where(active: true) || []
    else
      @products = Product.includes(:category).where(active: true)
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock_quantity, :category_id, :brand_id, :active)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">
    <!-- title -->
    <title><%= content_for(:title) || "Fruitkha" %></title>
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="/assets/img/favicon.png">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="/assets/css/all.min.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <!-- owl carousel -->
    <link rel="stylesheet" href="/assets/css/owl.carousel.css">
    <!-- magnific popup -->
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
    <!-- animate css -->
    <link rel="stylesheet" href="/assets/css/animate.css">
    <!-- mean menu css -->
    <link rel="stylesheet" href="/assets/css/meanmenu.min.css">
    <!-- main style -->
    <link rel="stylesheet" href="/assets/css/main.css">
    <!-- responsive -->
    <link rel="stylesheet" href="/assets/css/responsive.css">
  </head>
  <body>
    <!--PreLoader-->
    <div class="loader">
      <div class="loader-inner">
        <div class="circle"></div>
      </div>
    </div>
    <!--PreLoader Ends-->
    <!-- header -->
    <div class="top-header-area" id="sticker">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 text-center">
            <div class="main-menu-wrap">
              <!-- logo -->
              <div class="site-logo">
                <a href="/">
                  <img src="/assets/img/logo.png" alt="">
                </a>
              </div>
              <!-- logo -->
              <!-- menu start -->
              <nav class="main-menu">
                <ul>
                  <li class="<%= 'current-list-item' if current_page?(root_path) %>">
                    <%= link_to "Home", root_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(about_path) %>">
                    <%= link_to "About", about_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(news_path) %>">
                    <%= link_to "News", news_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(contact_path) %>">
                    <%= link_to "Contact", contact_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(shop_path) %>">
                    <%= link_to "Shop", shop_path %>
                  </li>
                  <li>
                    <div class="header-icons">
                      <% if admin_signed_in? %>
                        <span style="color: white;"><%= current_admin.email %></span> |
                        <%= link_to 'Logout', destroy_admin_session_path %>
                      <% else %>
                        <%= link_to 'Sign Up', new_admin_registration_path %> |
                        <%= link_to 'Login', new_admin_session_path %>
                      <% end %>
                      <%= link_to cart_path, class: "shopping-cart" do %>
                        <i class="fas fa-shopping-cart"></i>
                      <% end %>
                      <a class="mobile-hide search-bar-icon" href="#">
                        <i class="fas fa-search"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </nav>
              <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
              <div class="mobile-menu"></div>
              <!-- menu end -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end header -->
    <!-- search area -->
    <div class="search-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <span class="close-btn"><i class="fas fa-window-close"></i></span>
            <div class="search-bar">
              <div class="search-bar-tablecell">
                <h3>Search For:</h3>
                <input type="text" placeholder="Keywords">
                <button type="submit">Search <i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end search arewa -->


    <!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p><%= content_for?(:_1st) ? yield(:_1st) : "Default Title" %></p>
						<h1><%= content_for?(:_2nd) ? yield(:_2nd) : "Default Title" %></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->
    <%= yield %>


    <!-- copyright -->
    <div class="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
              Distributed By - <a href="https://themewagon.com/">Themewagon</a>
            </p>
          </div>
          <div class="col-lg-6 text-right col-md-12">
            <div class="social-icons">
              <ul>
                <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end copyright -->
    <!-- jquery -->
    <script src="/assets/js/jquery-1.11.3.min.js"></script>
    <!-- bootstrap -->
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- count down -->
    <script src="/assets/js/jquery.countdown.js"></script>
    <!-- isotope -->
    <script src="/assets/js/jquery.isotope-3.0.6.min.js"></script>
    <!-- waypoints -->
    <script src="/assets/js/waypoints.js"></script>
    <!-- owl carousel -->
    <script src="/assets/js/owl.carousel.min.js"></script>
    <!-- magnific popup -->
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <!-- mean menu -->
    <script src="/assets/js/jquery.meanmenu.min.js"></script>
    <!-- sticker js -->
    <script src="/assets/js/sticker.js"></script>
    <!-- main js -->
    <script src="/assets/js/main.js"></script>
    <!-- form validation js -->
    <script src="/assets/js/form-validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@rails/ujs@7.1.2/lib/assets/compiled/rails-ujs.min.js"></script>
    <script>
      Rails.start()
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">
    <!-- title -->
    <title>About</title>
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="/assets/img/favicon.png">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="/assets/css/all.min.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <!-- owl carousel -->
    <link rel="stylesheet" href="/assets/css/owl.carousel.css">
    <!-- magnific popup -->
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
    <!-- animate css -->
    <link rel="stylesheet" href="/assets/css/animate.css">
    <!-- mean menu css -->
    <link rel="stylesheet" href="/assets/css/meanmenu.min.css">
    <!-- main style -->
    <link rel="stylesheet" href="/assets/css/main.css">
    <!-- responsive -->
    <link rel="stylesheet" href="/assets/css/responsive.css">
  </head>
  <body>
    <!--PreLoader-->
    <div class="loader">
      <div class="loader-inner">
        <div class="circle"></div>
      </div>
    </div>
    <!--PreLoader Ends-->
    <!-- header -->
    <div class="top-header-area" id="sticker">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 text-center">
            <div class="main-menu-wrap">
              <!-- logo -->
              <div class="site-logo">
                <a href="/">
                  <img src="/assets/img/logo.png" alt="">
                </a>
              </div>
              <!-- logo -->
              <!-- menu start -->
              <nav class="main-menu">
                <ul>
                  <li class="<%= 'current-list-item' if current_page?(root_path) %>">
                    <%= link_to "Home", root_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(about_path) %>">
                    <%= link_to "About", about_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(news_path) %>">
                    <%= link_to "News", news_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(contact_path) %>">
                    <%= link_to "Contact", contact_path %>
                  </li>
                  <li class="<%= 'current-list-item' if current_page?(shop_path) %>">
                    <%= link_to "Shop", shop_path %>
                  </li>
                  <li>
                    <div class="header-icons">
                      <% if user_signed_in? %>
                        <span style="color: white;"><%= current_user.email %></span> |
                        <%= link_to 'Logout', destroy_user_session_path %>
                      <% else %>
                        <%= link_to 'Sign Up', new_user_registration_path %> |
                        <%= link_to 'Login', new_user_session_path %>
                      <% end %>
                      <%= link_to cart_path, class: "shopping-cart" do %>
                        <i class="fas fa-shopping-cart"></i>
                      <% end %>
                      <a class="mobile-hide search-bar-icon" href="#">
                        <i class="fas fa-search"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </nav>
              <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
              <div class="mobile-menu"></div>
              <!-- menu end -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end header -->
    <!-- search area -->
    <div class="search-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <span class="close-btn"><i class="fas fa-window-close"></i></span>
            <div class="search-bar">
              <div class="search-bar-tablecell">
                <h3>Search For:</h3>
                <input type="text" placeholder="Keywords">
                <button type="submit">Search <i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end search arewa -->
    <%= yield %>
    <!-- logo carousel -->
    <div class="logo-carousel-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="logo-carousel-inner">
              <div class="single-logo-item">
                <img src="/assets/img/company-logos/1.png" alt="">
              </div>
              <div class="single-logo-item">
                <img src="/assets/img/company-logos/2.png" alt="">
              </div>
              <div class="single-logo-item">
                <img src="/assets/img/company-logos/3.png" alt="">
              </div>
              <div class="single-logo-item">
                <img src="/assets/img/company-logos/4.png" alt="">
              </div>
              <div class="single-logo-item">
                <img src="/assets/img/company-logos/5.png" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end logo carousel -->
    <!-- footer -->
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer-box about-widget">
              <h2 class="widget-title">About us</h2>
              <p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-box get-in-touch">
              <h2 class="widget-title">Get in Touch</h2>
              <ul>
                <li>34/8, East Hukupara, Gifirtok, Sadan.</li>
                <li>support@fruitkha.com</li>
                <li>+00 111 222 3333</li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-box pages">
              <h2 class="widget-title">Pages</h2>
              <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/shop">Shop</a></li>
                <li><a href="/news">News</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-box subscribe">
              <h2 class="widget-title">Subscribe</h2>
              <p>Subscribe to our mailing list to get the latest updates.</p>
              <form action="index.html">
                <input type="email" placeholder="Email">
                <button type="submit"><i class="fas fa-paper-plane"></i></button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end footer -->
    <!-- copyright -->
    <div class="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
              Distributed By - <a href="https://themewagon.com/">Themewagon</a>
            </p>
          </div>
          <div class="col-lg-6 text-right col-md-12">
            <div class="social-icons">
              <ul>
                <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
                <li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end copyright -->
    <!-- jquery -->
    <script src="/assets/js/jquery-1.11.3.min.js"></script>
    <!-- bootstrap -->
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- count down -->
    <script src="/assets/js/jquery.countdown.js"></script>
    <!-- isotope -->
    <script src="/assets/js/jquery.isotope-3.0.6.min.js"></script>
    <!-- waypoints -->
    <script src="/assets/js/waypoints.js"></script>
    <!-- owl carousel -->
    <script src="/assets/js/owl.carousel.min.js"></script>
    <!-- magnific popup -->
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <!-- mean menu -->
    <script src="/assets/js/jquery.meanmenu.min.js"></script>
    <!-- sticker js -->
    <script src="/assets/js/sticker.js"></script>
    <!-- main js -->
    <script src="/assets/js/main.js"></script>
    <!-- form validation js -->
    <script src="/assets/js/form-validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@rails/ujs@7.1.2/lib/assets/compiled/rails-ujs.min.js"></script>
    <script>
      Rails.start()
    </script>
  </body>
</html>

app/views/pages/error_404.html.erb
		<% content_for :title, "404 Not Found" %>
    

    <%content_for :_1st, "Error" %>
    <%content_for :_2nd, "404 Not Found" %>
<!-- error section -->
<div class="full-height-section error-section">
  <div class="full-height-tablecell">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2 text-center">
          <div class="error-text">
            <i class="far fa-sad-cry"></i>
            <h1>Oops! Not Found.</h1>
            <p>The page you requested for is not found.</p>
            <a href="index.html" class="boxed-btn">Back to Home</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end error section -->

app/views/products/cat_products.html.erb
	<% content_for :title, @category.name %>
<%content_for :_1st, "Fresh and Organic" %>
<%content_for :_2nd, @category.name %>
<!-- products -->
<div class="product-section mt-150 mb-150">
  <div class="container">
    <div class="row product-lists">
      <% if @products.any? %>
        <% @products.each do |product| %>
          <div class="col-lg-4 col-md-6 text-center">
            <div class="single-product-item">
              <div class="product-image">
                <a href="#">
                  <img src="<%= product.image_path%>" alt="">
                </a>
              </div>
              <h3><%= product.name %></h3>
              <p class="product-price">
                <span>Per Item</span>
                <%= product.price %>$
              </p>
              <%= button_to add_to_cart_path(product.id),
              method: :post,
              class: "cart-btn" do %>
                <i class="fas fa-shopping-cart"></i> Add to Cart
              <% end %>
              <%# show the product %>
              <%= link_to "View Details", product_path(product), class: "cart-btn" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12 text-center">
          <h3>There are no products</h3>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="pagination-wrap">
          <ul>
            <li><a href="#">Prev</a></li>
            <li><a href="#">1</a></li>
            <li><a class="active" href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end products -->

app/views/products/index.html.erb
	<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <div class="breadcrumb-text">
          <h1><%= @category.name %></h1>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end breadcrumb section -->
<!-- products -->
<div class="product-section mt-150 mb-150">
  <div class="container">
    <div class="row product-lists">
      <% if @products.any? %>
        <% @products.each do |product| %>
          <div class="col-lg-4 col-md-6 text-center">
            <div class="single-product-item">
              <div class="product-image">
                <a href="#">
                  <img src="<%= product.image_path%>" alt="">
                </a>
              </div>
              <h3><%= product.name %></h3>
              <p class="product-price">
                <span>Per Item</span>
                <%= product.price %>$
              </p>
              <%= button_to add_to_cart_path(product.id),
              method: :post,
              class: "cart-btn" do %>
                <i class="fas fa-shopping-cart"></i> Add to Cart
              <% end %>
              <%# show the product %>
              <%= link_to "View Details", product_path(product), class: "cart-btn" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12 text-center">
          <h3>There are no products</h3>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="pagination-wrap">
          <ul>
            <li><a href="#">Prev</a></li>
            <li><a href="#">1</a></li>
            <li><a class="active" href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end products -->